# Generated by Django 4.1.7 on 2023-03-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=1000000000)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('b6', 'B6'), ('b12', 'B12')], default='b6', max_length=20)),
                ('etat', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('ncien', 'Ancien')], default='ancien', max_length=20)),
                ('stock', models.IntegerField()),
                ('number_register', models.CharField(max_length=255)),
            ],
        ),
    ]
