# Generated by Django 4.1.7 on 2023-03-16 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_commandes',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='items',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='total',
        ),
        migrations.AddField(
            model_name='commande',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
