# Generated by Django 4.1.7 on 2023-03-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_commande_date_commandes_remove_commande_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='users',
        ),
    ]
