# Generated by Django 4.1.7 on 2023-03-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_commande_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='Product',
        ),
    ]
